export const DAILY_PACK_LIMIT = 4;
export const DIGITAL_PACK_HISTORY_LIMIT = 40;
export const DIGITAL_ACTIVE_PACK_POOL_SIZE = 3;

export const CURATED_DIGITAL_PACKS = [
  {
    id: "digital-perfect-order",
    setId: "me3",
    name: "Perfect Order Pack",
    subtitle: "Top-end Mega Evolution pulls.",
    unlockCost: 1,
    packSize: 5,
    slotOdds: [
      { tier: "common", fallback: ["uncommon", "rare", "ultra"] },
      { tier: "common", fallback: ["uncommon", "rare", "ultra"] },
      { tier: "uncommon", fallback: ["common", "rare", "ultra"] },
      { tier: "rare", fallback: ["uncommon", "common", "ultra"] },
      { tier: "ultra", fallback: ["rare", "uncommon", "common"] },
    ],
  },
  {
    id: "digital-ascended-heroes",
    setId: "me2pt5",
    name: "Ascended Heroes Pack",
    subtitle: "Hero cards with a stronger ultra slot.",
    unlockCost: 1,
    packSize: 5,
    slotOdds: [
      { tier: "common", fallback: ["uncommon", "rare", "ultra"] },
      { tier: "uncommon", fallback: ["common", "rare", "ultra"] },
      { tier: "uncommon", fallback: ["common", "rare", "ultra"] },
      { tier: "rare", fallback: ["uncommon", "common", "ultra"] },
      { tier: "ultra", fallback: ["rare", "uncommon", "common"] },
    ],
  },
  {
    id: "digital-phantasmal-flames",
    setId: "me2",
    name: "Phantasmal Flames Pack",
    subtitle: "Recent chase cards with balanced odds.",
    unlockCost: 1,
    packSize: 5,
    slotOdds: [
      { tier: "common", fallback: ["uncommon", "rare", "ultra"] },
      { tier: "common", fallback: ["uncommon", "rare", "ultra"] },
      { tier: "uncommon", fallback: ["common", "rare", "ultra"] },
      { tier: "rare", fallback: ["uncommon", "common", "ultra"] },
      { tier: "ultra", fallback: ["rare", "uncommon", "common"] },
    ],
  },
  {
    id: "digital-mega-evolution",
    setId: "me1",
    name: "Mega Evolution Pack",
    subtitle: "Base Mega Evolution digital booster.",
    unlockCost: 1,
    packSize: 5,
    slotOdds: [
      { tier: "common", fallback: ["uncommon", "rare", "ultra"] },
      { tier: "common", fallback: ["uncommon", "rare", "ultra"] },
      { tier: "uncommon", fallback: ["common", "rare", "ultra"] },
      { tier: "rare", fallback: ["uncommon", "common", "ultra"] },
      { tier: "ultra", fallback: ["rare", "uncommon", "common"] },
    ],
  },
  {
    id: "digital-white-flare",
    setId: "rsv10pt5",
    name: "White Flare Pack",
    subtitle: "Scarlet & Violet special set with flashy pulls.",
    unlockCost: 1,
    packSize: 5,
    slotOdds: [
      { tier: "common", fallback: ["uncommon", "rare", "ultra"] },
      { tier: "common", fallback: ["uncommon", "rare", "ultra"] },
      { tier: "uncommon", fallback: ["common", "rare", "ultra"] },
      { tier: "rare", fallback: ["uncommon", "common", "ultra"] },
      { tier: "ultra", fallback: ["rare", "uncommon", "common"] },
    ],
  },
  {
    id: "digital-black-bolt",
    setId: "zsv10pt5",
    name: "Black Bolt Pack",
    subtitle: "Scarlet & Violet special set companion pack.",
    unlockCost: 1,
    packSize: 5,
    slotOdds: [
      { tier: "common", fallback: ["uncommon", "rare", "ultra"] },
      { tier: "common", fallback: ["uncommon", "rare", "ultra"] },
      { tier: "uncommon", fallback: ["common", "rare", "ultra"] },
      { tier: "rare", fallback: ["uncommon", "common", "ultra"] },
      { tier: "ultra", fallback: ["rare", "uncommon", "common"] },
    ],
  },
];
