const AppImages = {
  icon: require('../assets/images/icon.png'),
  splash: require('../assets/images/splash.png'),
  // alphaIcon: require('../assets/images/iconalpha.png'),
  // logo: require('../assets/images/logo.png'),
  alphaPokemonIcon: require('../assets/images/gameIcons/alpha_pokemon.png'),
  shinyPokemonIcon: require('../assets/images/gameIcons/shiny_pokemon.png'),
  zaPokemonLogo: require('../assets/images/gameIcons/logo_pokemon_legends_za.png'),
  arceusPokemonLogo: require('../assets/images/gameIcons/logo_pokemon_legends_arceus.png'),
  svPokemonLogo: require('../assets/images/gameIcons/logo_pokemon_sv.png'),
  bdspPokemonLogo: require('../assets/images/gameIcons/logo_pokemon_bdsp.png'),
  caughtPalworldIcon: require('../assets/images/gameIcons/caught_palworld.png'),
  alphaPalworldIcon: require('../assets/images/gameIcons/alpha_palworld.png'),
  luckyPalworldIcon: require('../assets/images/gameIcons/lucky_palworld.png'),
  alphaDinoIcon: require('../assets/images/alts/icon-dino-alpha.png'),
  alphaFoxIcon: require('../assets/images/alts/icon-fox-alpha.png'),
  foxIcon: require('../assets/images/alts/icon-fox.png'),
  foxImage: require('../assets/images/alts/fox.png'),
  dinoIcon: require('../assets/images/alts/icon-dino.png'),
  dinoImage: require('../assets/images/alts/dino.png'),
  alphaDragonIcon: require('../assets/images/alts/icon-dragon-alpha.png'),
  dragonIcon: require('../assets/images/alts/icon-dragon.png'),
  dragonImage: require('../assets/images/alts/dragon.png'),
};

export default AppImages;
